print(True)
print(False)
print('petik tunggal')
print("petik ganda")
print(69)
print(3.14)
print()
print()
print([1, 5, 6, 7, 8, 9])
print(["satu", "dua", "sembilan"])
print((1,2,3,4,5))
print(("satu", "dua", "tiga"))
print({"nama":"Andi", 'umur' :20})
biodata = {"nama":"Andi", 'umur':21}
print(biodata)
print(type(biodata))
